// packages/core/src/channels/slack-bot.ts
// Slack Bot 推送通道

import { Insight } from '../types'

export interface SlackConfig {
  webhookUrl: string
  channel?: string
}

export class SlackBot {
  private config: SlackConfig

  constructor(config: SlackConfig) {
    this.config = config
  }

  // 发送洞察到 Slack
  async sendInsight(insight: Insight): Promise<boolean> {
    const blocks = this.formatInsight(insight)

    try {
      const response = await fetch(this.config.webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          channel: this.config.channel,
          blocks,
          text: `VertexHub: ${insight.type} insight`,
        }),
      })

      return response.ok
    } catch (error) {
      console.error('Slack send error:', error)
      return false
    }
  }

  // 格式化洞察为 Slack Block Kit
  private formatInsight(insight: Insight): any[] {
    const blocks: any[] = []

    // Header
    blocks.push({
      type: 'header',
      text: {
        type: 'plain_text',
        text: this.getHeaderText(insight),
        emoji: true,
      },
    })

    // Divider
    blocks.push({ type: 'divider' })

    // Content based on type
    switch (insight.type) {
      case 'daily':
        blocks.push(...this.formatDailyInsight(insight))
        break
      case 'weekly':
        blocks.push(...this.formatWeeklyInsight(insight))
        break
      case 'anomaly':
        blocks.push(...this.formatAnomalyInsight(insight))
        break
      case 'deep_dive':
        blocks.push(...this.formatDeepDiveInsight(insight))
        break
    }

    // Footer
    blocks.push({
      type: 'context',
      elements: [
        {
          type: 'mrkdwn',
          text: `Generated by VertexHub at ${new Date().toLocaleString()}`,
        },
      ],
    })

    return blocks
  }

  private getHeaderText(insight: Insight): string {
    switch (insight.type) {
      case 'daily':
        return '📊 Daily Digest'
      case 'weekly':
        return '📋 Weekly Summary'
      case 'anomaly':
        return '🚨 Anomaly Alert'
      case 'deep_dive':
        return '🔍 Deep Dive Analysis'
      default:
        return '📢 VertexHub Insight'
    }
  }

  private formatDailyInsight(insight: Insight): any[] {
    const blocks: any[] = []
    const { summary, metrics, events } = insight.content

    if (summary) {
      blocks.push({
        type: 'section',
        text: { type: 'mrkdwn', text: summary },
      })
    }

    if (metrics) {
      const metricsText = Object.entries(metrics)
        .map(([key, value]) => `*${key}*: ${value}`)
        .join('  |  ')

      blocks.push({
        type: 'section',
        text: { type: 'mrkdwn', text: metricsText },
      })
    }

    if (events && events.length > 0) {
      const eventsText = events
        .slice(0, 5)
        .map((e: any) => `• ${e.type}: ${e.title}`)
        .join('\n')

      blocks.push({
        type: 'section',
        text: { type: 'mrkdwn', text: `*Recent Activity:*\n${eventsText}` },
      })
    }

    return blocks
  }

  private formatWeeklyInsight(insight: Insight): any[] {
    const blocks: any[] = []
    const { progress, blockers, risks, suggestions } = insight.content

    if (progress && progress.length > 0) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Key Progress:*\n${progress.map((p: string) => `✅ ${p}`).join('\n')}`,
        },
      })
    }

    if (blockers && blockers.length > 0) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Blockers:*\n${blockers.map((b: string) => `🚫 ${b}`).join('\n')}`,
        },
      })
    }

    if (risks && risks.length > 0) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Risks:*\n${risks.map((r: string) => `⚠️ ${r}`).join('\n')}`,
        },
      })
    }

    if (suggestions && suggestions.length > 0) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Suggestions:*\n${suggestions.map((s: string) => `💡 ${s}`).join('\n')}`,
        },
      })
    }

    return blocks
  }

  private formatAnomalyInsight(insight: Insight): any[] {
    const blocks: any[] = []
    const { message, conflicts } = insight.content

    if (message) {
      blocks.push({
        type: 'section',
        text: { type: 'mrkdwn', text: `🚨 ${message}` },
      })
    }

    if (conflicts && conflicts.length > 0) {
      const conflictsText = conflicts
        .map((c: any) => `• *${c.field}* (${c.severity}): ${c.details?.length || 0} conflicts`)
        .join('\n')

      blocks.push({
        type: 'section',
        text: { type: 'mrkdwn', text: conflictsText },
      })
    }

    return blocks
  }

  private formatDeepDiveInsight(insight: Insight): any[] {
    const blocks: any[] = []
    const { status, timeline, risks, recommendations } = insight.content

    if (status) {
      const statusEmoji = status === 'on_track' ? '✅' : status === 'at_risk' ? '⚠️' : '🚫'
      blocks.push({
        type: 'section',
        text: { type: 'mrkdwn', text: `${statusEmoji} *Status:* ${status}` },
      })
    }

    if (timeline) {
      blocks.push({
        type: 'section',
        text: { type: 'mrkdwn', text: `📅 *Timeline:* ${timeline}` },
      })
    }

    if (risks && risks.length > 0) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Risks:*\n${risks.map((r: string) => `⚠️ ${r}`).join('\n')}`,
        },
      })
    }

    if (recommendations && recommendations.length > 0) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Recommendations:*\n${recommendations.map((r: string) => `💡 ${r}`).join('\n')}`,
        },
      })
    }

    return blocks
  }
}
